[build]
  publish = "public"
  command = "hugo"

  [build.environment]
    HUGO_THEME = "repo"
    HUGO_VERSION = "0.55"
    HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
